### ISSUE TITLE
Compile fails on torch 2.14 due to hardcoded -std=c++17 compiler option (needs to be -std=c++20)

### ISSUE THREAD

**Issue by phaserblast** [pawel-mazurkiewicz/ComfyUI-AppleSilicon-FP8#34]
FYI: I was getting a compilation error running torch==2.14 about requiring -std=c++20 on a Macbook M5. I had to edit this file and change the compiler flag:
_patches/int8_ext/loader.py line 109:
```
// change this:
//extra_cflags=["-std=c++17, "-ObjC++"],
// to this:
extra_cflags=["-std=c++20", "-ObjC++"],
```
Now the kernels compile okay on the first run.

**Comment by AstroPig7** [comment]
I had the same problem before downgrading PyTorch to 2.13. The nightly build is the only one where I encountered this problem.

**Comment by pawel-mazurkiewicz** [comment]
Thanks @phaserblast, and @AstroPig7 for confirming. You diagnosed it correctly. torch 2.14's JIT builder already passes `-std=c++20`, and our hardcoded `-std=c++17` came after it and won. It turned out to be wider than the int8 loader: on torch 2.14 the **fp8 and int4 kernels failed to build too**, and silently fell back to the slow paths.

The fix is in #38. Rather than bumping the flag to `c++20`, it drops `-std` entirely, so the build always uses the standard the installed torch was built with. Verified on an M5 Max / macOS 27.0: all three kernels build on torch 2.14.0 and 2.11.0, and the kernel test suites pass on 2.14.0 (including the bit-exact int8 check).

Until it's merged, your one-line edit is safe to keep. The update will replace it cleanly.

**Comment by pawel-mazurkiewicz** [comment]
Released in [v1.3.3](https://github.com/pawel-mazurkiewicz/ComfyUI-AppleSilicon-FP8/releases/tag/v1.3.3). The Metal kernels now build on torch 2.14, and the manual `-std=c++20` edit is no longer needed. Thanks @phaserblast and @AstroPig7!
